### ISSUE TITLE
Alphine or Ubuntu

### ISSUE THREAD

**Issue by ccfiel** [ianneub/docker-frappe#5]
@ianneub I have notice you have to folder alphine os and for ubuntu. Which would you recommend to used? Thanks in advance.

**Comment by ianneub** [comment]
At this time I would not recommend using either. I am not maintaining either one. 

With that said, you could choose either one that you are comfortable with. Alpine will take up less disk space, so images can be downloaded faster. Ubuntu might be more familiar. At this time though, it is up to you or the community to continue developing it, as I am not using ERPNext anymore.

**Comment by ccfiel** [comment]
@ianneub thanks for the answer. Why are you not using ERPNext anymore if you don't mind asking :)

**Comment by ianneub** [comment]
We decided it wasn't worth the time to implement and get used to a new system. While I was able to get it to work with Docker, it seems like it doesn't really want to be deployed that way. Since it is not supported upstream, we didn't want to be on the fringe of an open source project.

Hopefully over time they will embrace Docker :)
